@startuml 1

    !theme hacker
    skinparam BackgroundColor black
    title "ER Diagram"

    object User {
        username (U): str(50)
        email (U): str(50)
        password: str(50)
        first_name: str(50)
        last_name: str(50)
    }

@enduml

@startuml 2

    !theme hacker
    skinparam BackgroundColor black
    title "Sequence Diagram"

    actor User
    participant urls
    participant users.urls
    participant users.views.post
    database "User DB"

    == POST /users ==
    User             ->  urls             : POST /users
    urls             ->  users.urls       : POST /
    users.urls       ->  users.views.post : POST /
    users.views.post ->  "User DB"        : INSERT
    users.views.post <-- "User DB"        : SUCCESS
    User             <-- users.views.post : 201 Created
@enduml

@startuml 3

    !theme hacker
    skinparam BackgroundColor black
    title "Sequence Diagram"

    actor User
    participant urls
    participant auths.urls
    participant auths.views.post
    database Session

    == POST /auths ==
    User             ->  urls             : POST /auths
    urls             ->  auths.urls       : POST /
    auths.urls       ->  auths.views.post : POST /
    auths.views.post ->  Session          : INSERT
    auths.views.post <-- Session          : SUCCESS
    User             <-- auths.views.post : 200 OK
@enduml