@startuml 1

    !theme hacker
    skinparam BackgroundColor black
    title "ER Diagram"

    object User {
        username (U): str(50)
        email (U): str(50)
        password: str(50)
        first_name: str(50)
        last_name: str(50)
    }

    object Item {
        name: str(50)
        description: str(50)
        seller: User
        mrp: int // paise
        price: int // paise
    }

    User <|-- Item : is sold by

@enduml

@startuml 2

    !theme hacker
    skinparam BackgroundColor black
    title "Sequence Diagram"

    actor User
    participant urls
    participant users.urls
    participant users.views.post
    database "User DB"

    == post /users ==
    User             ->  urls             : post /users
    urls             ->  users.urls       : post /
    users.urls       ->  users.views.post : post /
    users.views.post ->  "User DB"        : INSERT
    users.views.post <-- "User DB"        : SUCCESS
    User             <-- users.views.post : 201 Created
@enduml

@startuml 3

    !theme hacker
    skinparam BackgroundColor black
    title "Sequence Diagram"

    actor User
    participant urls
    participant auths.urls
    participant auths.views.post
    database Session

    == post /auths ==
    User             ->  urls             : post /auths
    urls             ->  auths.urls       : post /
    auths.urls       ->  auths.views.post : post /
    auths.views.post ->  Session          : INSERT
    auths.views.post <-- Session          : SUCCESS
    User             <-- auths.views.post : 200 OK
@enduml

@startuml 4

    !theme hacker
    skinparam BackgroundColor black
    title "Sequence Diagram"

    actor User
    participant urls
    participant items.urls
    participant items.views.post
    database Item

    == post /items ==
    User             ->  urls             : post /items
    urls             ->  items.urls       : post /
    items.urls       ->  items.views.post : post /
    items.views.post ->  Item             : INSERT
    items.views.post <-- Item             : SUCCESS
    User             <-- items.views.post : 200 OK
@enduml