@startuml 1

    !theme hacker
    skinparam BackgroundColor black
    title "ER Diagram"

    object User {
        username (U): str(50)
        email (U): str(50)
        password: str(50)
        first_name: str(50)
        last_name: str(50)
    }

    object .models.Item {
        name: str(50)
        description: str(500)
        seller: User
        mrp: int // paise
        price: int // paise
    }

    User <|-- .models.Item : is sold by

@enduml

@startuml 2

    !theme hacker
    skinparam BackgroundColor black
    title "Sequence Diagram"

    actor User
    participant urls
    box users
    participant .urls
    participant .views.post
    database .models.User

    == post /users ==
    User        ->   urls        : post /users
    urls        ->  .urls        : post /
    .urls       ->  .views.post  :
    .views.post ->  .models.User : INSERT
    .views.post <-- .models.User : SUCCESS
    User        <-- .views.post  : 201 Created
@enduml

@startuml 3

    !theme hacker
    skinparam BackgroundColor black
    title "Sequence Diagram"

    actor User
    participant urls
    box auths
    participant .urls
    participant .views.post
    end box
    database Session

    == post /users ==
    == post /auths ==
    User        ->  urls        : post /auths
    urls        ->  .urls       : post /
    .urls       ->  .views.post :
    .views.post ->  Session     : INSERT
    .views.post <-- Session     : SUCCESS
    User        <-- .views.post : 200 OK
@enduml

@startuml 4

    !theme hacker
    skinparam BackgroundColor black
    title "Sequence Diagram"

    actor User
    participant urls
    box items
    participant .urls
    participant .views.post
    database .models.Item

    == post /users ==
    == post /auths ==
    == post /items ==
    User        ->  urls         : post /items
    urls        ->  .urls        : post /
    .urls       ->  .views.post  :
    .views.post ->  .models.Item : INSERT
    .views.post <-- .models.Item : SUCCESS
    User        <-- .views.post  : 201 Created
@enduml

@startuml 5

    !theme hacker
    skinparam BackgroundColor black
    title "Sequence Diagram"

    actor User
    participant urls
    box items
    participant .urls
    participant views.get
    participant serializers.ItemSerializer
    database .models.Item

    == post /users ==
    == post /auths ==
    == post /items ==
    == get /items ==
    User      ->  urls                       : get /items
    urls      ->  .urls                      : get /
    .urls     ->  views.get                  :
    views.get ->  .models.Item               : SELECT
    views.get <-- .models.Item               : Items
    views.get ->  serializers.ItemSerializer : Items
    views.get <-- serializers.ItemSerializer : Serialized Items
    User      <-- views.get                  : 200 OK
    User      <-- views.get                  : {items: {id: item, ...}}
@enduml